### PR TITLE
LUTs that define correspondence between ALCT-CLCT combination code and the resulting best and second best LCT

### PR DESCRIPTION
**Pull request by dildick**
Not yet needed by a current cms-sw pull request.

### CODE REVIEW

**Comment by mrodozov** [comment]
allow @dildick test rights

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by mrodozov** [comment]
+externals

**Comment by dildick** [comment]
Thanks for the quick turn-around.

**Pull request merged**
