### PR TITLE
Lookup tables for CCLUTv2

### PR DESCRIPTION
**Pull request by dildick**
## CCLUT Version 2.0 (under directory CCLUTv2)

This repository holds lookup-tables which map a pattern number and a 11-bit comparator code onto an unsigned 4-bit position offset and a 5-bit slope. In the current form, there are 5 patterns (0 through 4) and 2048 comparator codes. LUTs are also available with floating point values (for reference). A third set of LUTs convert the Run-1/2 patterns to Run-3 patterns.

The firmware dataword for each pattern and comparator code is 9 bits long:
   - [3:0] is slope value
   - [4] is slope sign
   - [8:5] is position offset

@tahuang1991

### CODE REVIEW

**Comment by smuzaffar** [comment]
please test

**Comment by dildick** [comment]
@smuzaffar Can this be merged?

**Comment by smuzaffar** [comment]
@rekovic, @cecilecaillol  any objections?

**Comment by smuzaffar** [comment]
@rekovic, @cecilecaillol , note that these are all new data files. 
@dildick , is there any cmssw PR to use/test these?

**Comment by dildick** [comment]
This is not for startup Run-3, but most likely for later in the Run. But the files aren't used by the code yet.I will make a PR later.

**Comment by smuzaffar** [comment]
@cecilecaillol @epalencia @rekovic Can you please review this cms-data PR?

**Comment by cecilecaillol** [comment]
@eyigitba @giovanni-mocellin Sven was working on this PR and mentioned these LUTs are not used in the code yet. Do you know if it is still the case and what the plan is? Should we merge this?

**Comment by cecilecaillol** [comment]
@smuzaffar This PR can be closed without merging.

**Comment by eyigitba** [comment]
@cecilecaillol sorry for the delayed response. I don't really know the details of this. I think it's ok to close it since it won't be used immediately. We can revisit it later.

**Pull request closed without merging**
