### PR TITLE
GEM-CSC slope correction LUTs

### PR DESCRIPTION
**Pull request by rathjd**
Initial commit of GEM-CSC slope correction LUTs, using the slope values from the CSC ME1/1 chamber to shift the expected position on the facing GE1/1 chambers in phi in 1/8th strip coordinates in both hexadecimal and decimal versions. Further details in the amended README.

### CODE REVIEW

**Comment by dildick** [comment]
@cecilecaillol Can this be merged?

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by dildick** [comment]
Thanks!

**Comment by mrodozov** [comment]
@dildick this are new files but is there anything usign them (cmssw) ?

**Comment by dildick** [comment]
The LUTs go in first. In a few weeks we will be putting in a PR with the code that uses them in the GEM-CSC integrated local trigger.

**Comment by dildick** [comment]
Hi, can this be merged?

**Pull request merged**
