### PR TITLE
New binning for Run-3 CLCT slope

### PR DESCRIPTION
**Pull request by dildick**
New binning for Run-3 CLCT slope. See also https://github.com/cms-sw/cmssw/pull/33380. LUTs generated with `L1Trigger/CSCTriggerPrimitives/test/macros/CCLUTLinearFitWriter.cpp`.

### CODE REVIEW

**Comment by dildick** [comment]
@tahuang1991 You can pick up these slope lookup tables for the firmware.

**Comment by mrodozov** [comment]
@dildick are the relevant changes for this in 33380 ?

**Comment by dildick** [comment]
Yes, the new binning is reflected in these new LUTs for the CSC trigger

**Comment by mrodozov** [comment]
please test
the cmssw pr should be in the latest IB so lets check it

**Comment by dildick** [comment]
it should pass, the Run-3 CSC local trigger is not switched on yet

**Comment by mrodozov** [comment]
@dildick what about the comparison diffs ?

**Comment by dildick** [comment]
Looks like just about everything is failing for WF 140.53

Screen Shot 2021-04-13 at 1 39 06 PM

Messagelogger failures for 10224.0, and pixel failures for 8.0.

**Comment by mrodozov** [comment]
please test
lets check if its genuine failure

**Comment by mrodozov** [comment]
it might have been another eos/xrootd glitch. it's gone now. this look ok

**Comment by mrodozov** [comment]
+externals

**Comment by dildick** [comment]
@mrodozov Thanks.

**Pull request merged**
