### PR TITLE
Update of ME1/1 LUTs. GEM-CSC LUTs with M9 GE2/1 geometry

### PR DESCRIPTION
**Pull request by dildick**
* LUTs to map wiregroup onto min and max half-strip number that it crosses in ME1/1. 
* LUTs for 16 partition GE21. 
* Split GEMCSC LUTs by layer. 
* Move to subdirectories (similar files ending in .mem)
   * CCLUT
      * CSCComparatorCodePatternConversionLUT_pat0_v1.txt
      * CSCComparatorCodePatternConversionLUT_pat1_v1.txt
      * CSCComparatorCodePatternConversionLUT_pat2_v1.txt
      * CSCComparatorCodePatternConversionLUT_pat3_v1.txt
      * CSCComparatorCodePatternConversionLUT_pat4_v1.txt
      * CSCComparatorCodePosOffsetLUT_pat0_float_v1.txt
      * CSCComparatorCodePosOffsetLUT_pat0_v1.txt
      * CSCComparatorCodePosOffsetLUT_pat1_float_v1.txt
      * CSCComparatorCodePosOffsetLUT_pat1_v1.txt
      * CSCComparatorCodePosOffsetLUT_pat2_float_v1.txt
      * CSCComparatorCodePosOffsetLUT_pat2_v1.txt
      * CSCComparatorCodePosOffsetLUT_pat3_float_v1.txt
      * CSCComparatorCodePosOffsetLUT_pat3_v1.txt
      * CSCComparatorCodePosOffsetLUT_pat4_float_v1.txt
      * CSCComparatorCodePosOffsetLUT_pat4_v1.txt
      * CSCComparatorCodeSlopeLUT_pat0_float_v1.txt
      * CSCComparatorCodeSlopeLUT_pat0_v1.txt
      * CSCComparatorCodeSlopeLUT_pat1_float_v1.txt
      * CSCComparatorCodeSlopeLUT_pat1_v1.txt
      * CSCComparatorCodeSlopeLUT_pat2_float_v1.txt
      * CSCComparatorCodeSlopeLUT_pat2_v1.txt
      * CSCComparatorCodeSlopeLUT_pat3_float_v1.txt
      * CSCComparatorCodeSlopeLUT_pat3_v1.txt
      * CSCComparatorCodeSlopeLUT_pat4_float_v1.txt
      * CSCComparatorCodeSlopeLUT_pat4_v1.txt  
   * GEMCSC
      * GEMCSCLUT_pad_es_ME1a_even.txt
      * GEMCSCLUT_pad_es_ME1a_odd.txt
      * GEMCSCLUT_pad_es_ME1b_even.txt
      * GEMCSCLUT_pad_es_ME1b_odd.txt
      * GEMCSCLUT_pad_es_ME21_even.txt
      * GEMCSCLUT_pad_es_ME21_odd.txt
      * GEMCSCLUT_pad_hs_ME1a_even.txt
      * GEMCSCLUT_pad_hs_ME1a_odd.txt
      * GEMCSCLUT_pad_hs_ME1b_even.txt
      * GEMCSCLUT_pad_hs_ME1b_odd.txt
      * GEMCSCLUT_pad_hs_ME21_even.txt
      * GEMCSCLUT_pad_hs_ME21_odd.txt
      * GEMCSCLUT_roll_l1_max_wg_ME11_even.txt
      * GEMCSCLUT_roll_l1_max_wg_ME11_odd.txt
      * GEMCSCLUT_roll_l1_max_wg_ME21_even.txt
      * GEMCSCLUT_roll_l1_max_wg_ME21_odd.txt
      * GEMCSCLUT_roll_l1_min_wg_ME11_even.txt
      * GEMCSCLUT_roll_l1_min_wg_ME11_odd.txt
      * GEMCSCLUT_roll_l1_min_wg_ME21_even.txt
      * GEMCSCLUT_roll_l1_min_wg_ME21_odd.txt
      * GEMCSCLUT_roll_l2_max_wg_ME11_even.txt
      * GEMCSCLUT_roll_l2_max_wg_ME11_odd.txt
      * GEMCSCLUT_roll_l2_max_wg_ME21_even.txt
      * GEMCSCLUT_roll_l2_max_wg_ME21_odd.txt
      * GEMCSCLUT_roll_l2_min_wg_ME11_even.txt
      * GEMCSCLUT_roll_l2_min_wg_ME11_odd.txt
      * GEMCSCLUT_roll_l2_min_wg_ME21_even.txt
      * GEMCSCLUT_roll_l2_min_wg_ME21_odd.txt
   * ME11
      * CSCLUT_wg_max_hs_ME1a.txt
      * CSCLUT_wg_max_hs_ME1a_ganged.txt
      * CSCLUT_wg_max_hs_ME1b.txt
      * CSCLUT_wg_min_hs_ME1a.txt
      * CSCLUT_wg_min_hs_ME1a_ganged.txt
      * CSCLUT_wg_min_hs_ME1b.txt
      
FYI @tahuang1991.

### CODE REVIEW

**Comment by dildick** [comment]
This will replace LUTs previously hard-coded in C++

**Comment by dildick** [comment]
Note to self: I also need to put in LUTs for ME2/1 with 8 rolls, and 16 rolls separately...

**Comment by dildick** [comment]
I also need to move all LUTs with `CSCComparator*` to CCLUT, but a separate PR to CMSSW is needed for that.

**Comment by dildick** [comment]
@cecilecaillol Can this be merged?

**Comment by cecilecaillol** [comment]
please test

**Comment by dildick** [comment]
@cecilecaillol Sorry about that. In one of my commits I had introduced a mistake.

**Comment by dildick** [comment]
I updated the description so it's clearer what i'm doing. Three things: 1) add new LUTs specifically for ME1/1. 2) update GEMCSC LUTs, in part because the GE2/1 geometry changes to 16 eta partitions. 3) Move LUTs to specific subdirectories.

**Comment by mrodozov** [comment]
please test

**Comment by dildick** [comment]
On last thing I had to fix is that some GE2/1 eta partitions fail to be matched to ME2/1 wiregroups. This is because an underlying function in CMSSW, the CSC layer geometry, fails to provide a reasonable number. I.e. GEM eta partitions in the middle of the chamber would map onto a wiregroup at the bottom of the CSC chamber, which does not make sense. I had to update my  LUT analyzer with a manual fix approximating the mapping.

**Comment by dildick** [comment]
The analyzer is this one: https://github.com/cms-sw/cmssw/blob/master/L1Trigger/CSCTriggerPrimitives/test/GEMCSCLUTAnalyzer.cc, but it does not contain the fix yet
```
...
    // override for cases when the function "wireGroup" fails to provide the
    // wiregroup number
    const int GEM_layer = roll->id().layer();
    const int GEM_roll = roll->id().roll();
    if (roll->isGE21() and GEM_layer == 1) {
      // L1 - max
      if (GEM_roll == 10)
        wg_top = 45;
      // L1 - min
      if (GEM_roll == 4)
        wg_bottom = 80;
      if (GEM_roll == 9)
        wg_bottom = 46;
    }
    lut.emplace_back(wg_bottom, wg_top);
  }
...
```

**Comment by mrodozov** [comment]
allow @dildick test rights

**Comment by dildick** [comment]
please test

**Comment by dildick** [comment]
There should be no difference in any workflow: ME1/1 LUTs and GEM-CSC LUTs are currently still hard-coded in C++ in CMSSW. In a future PR, I'll remove those and load the ones in cms-data instead.

**Comment by dildick** [comment]
> allow @dildick test rights

@mrodozov I guess the test rights only apply to cms-data, not cms-sw?

**Comment by ptcox** [comment]
Hi Sven,

Can you expand on "an underlying function in CMSSW, the CSC layer 
geometry, fails to provide a reasonable number"
AFAIK the CSCLayerGeometry returns correct values for all sane input. 
Are you sure you're not misunderstanding whatever function you mean?

Tim

Sven Dildick wrote on 4/26/21 23:06:

**Comment by mrodozov** [comment]
they apply only to this PR :)

**Comment by dildick** [comment]
@ptcox I noticed that some wires in ME2/1 are not connected to a wiregroup in CMSSW. I called this function 
```
  /**
   * Wire group containing a given wire
   */
  int wireGroup(int wire) const { return theWireTopology->wireGroup(wire); }
```
on wire 222 in ME2/1. I can't remember now if the chamber was even numbered or odd numbered. But ```wireGroup(222)``` returns 0. Now it could be, as you say, that 222 is simply not sane input. In any case, I had to manually fix a lookup table that translates radial positions of GEM eta partitions into radial positions in the CSC wiregroup plane.

**Comment by ptcox** [comment]
I think you may be misinterpreting what the function is trying to do. 
See the comments in CSCGangedWireGouping.h:

  * All 'wire'-related values refer to 'virtual wires' which cover the
  * face of the detector. All 'wire-group' values refer to actual
  * active (in principle) read out channels.

There are gaps in the wire groups: e.g. in ME2/1 there are 43 groups of 
5 wires, then 1 group of 2 wires, then a 6-wire gap, then 1 group of 2 
wires, then 19 groups of 5 wires, etc. etc (see 
https://twiki.cern.ch/twiki/pub/CMS/CSCDPGGeometry/csc_wire_groups_100928.pdf). 

The (virtual) wire '222' corresponds to a position where there is a gap, 
the 6-wire gap mentioned above, and so it does not belong to a wiregroup.
Since we never deal with individual wires I chose not to number the real 
wires consecutively, but instead consider a plane of virtual wires, 
equi-spaced across the wire plane and then assign those to a wire group 
, or not (if they're in a gap). Then I could easily implement 
geometrical calculations for a wire group in terms of the virtual wires 
assigned to that wire group.

How are you getting the '222' to start with?

Regards, Tim

Sven Dildick wrote on 4/27/21 14:05:

**Comment by dildick** [comment]
Hi Tim,

In this analyzer I wrote to build lookup tables for the GEM-CSC trigger (https://github.com/dildick/cmssw/blob/a72dbbb3ac6d925f8c8c14fcc3befd670563bc4d/L1Trigger/CSCTriggerPrimitives/test/GEMCSCLUTAnalyzer.cc#L451-L485), I have a function 

```python
  const CSCLayerGeometry* keyLayerGeometry(keyLayer->geometry());
  for (const auto& roll : gemChamber->etaPartitions()) {
    const float half_striplength(roll->specs()->specificTopology().stripLength() / 2.);
    const LocalPoint lp_top(0., half_striplength, 0.);
    const LocalPoint lp_bottom(0., -half_striplength, 0.);

    const GlobalPoint gp_top(roll->toGlobal(lp_top));
    const GlobalPoint gp_bottom(roll->toGlobal(lp_bottom));

    const LocalPoint lp_csc_top(keyLayer->toLocal(gp_top));
    const LocalPoint lp_csc_bottom(keyLayer->toLocal(gp_bottom));

    const int wire_top(keyLayerGeometry->nearestWire(lp_csc_top));
    const int wire_bottom(keyLayerGeometry->nearestWire(lp_csc_bottom));

    int wg_top(keyLayerGeometry->wireGroup(wire_top));
    int wg_bottom(keyLayerGeometry->wireGroup(wire_bottom));

    // override for cases when the function "wireGroup" fails to provide the
    // wiregroup number
    const int GEM_layer = roll->id().layer();
    const int GEM_roll = roll->id().roll();
    if (roll->isGE21() and GEM_layer == 1) {
      // L1 - max
      if (GEM_roll == 10)
        wg_top = 45;
      // L1 - min
      if (GEM_roll == 4)
        wg_bottom = 80;
      if (GEM_roll == 9)
        wg_bottom = 46;
    }
    lut.emplace_back(wg_bottom, wg_top);
  }
}
```

It translates the edges of the eta partition in the y-coordinate to GEM local points, to global points, to CSC local points, to wire numbers, and ultimately to wiregroup numbers. The transition of CSC local point to wire returns 0 for those cases where I'm in a gap region. For those case I approximate the corresponding wiregroup.

**Comment by ptcox** [comment]
Thanks for the explanation. I understand. You really need a 
'nearestWireGroup(wire)' function.

Sven Dildick wrote on 4/27/21 17:29:

**Comment by dildick** [comment]
Indeed, Tim. That is correct.

**Comment by qliphy** [comment]
cms-sw/cmssw#33570

**Comment by dildick** [comment]
@cecilecaillol Can this be merged? Thanks.

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#33617

**Comment by cecilecaillol** [comment]
+l1

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
I have merged this and there will be cms-sw/cmsdist#6872 should include. cms-sw/cmssw#33617 should be merged along with cms-sw/cmsdist#6872

**Pull request merged**
