### PR TITLE
Add LUTs for CSC stub position offset and bending value.

### PR DESCRIPTION
**Pull request by dildick**
This repository holds look-up-tables which, in their current form, map a 12-bit comparator code onto a floating point number. That can either be a position offset or a slope. In the current form, there are 5 patterns (0 through 4) and 4096 comparator codes. For the position offset, there is an ideal case and a realistic case. The ideal case does not take into account a global offset from alignment effects, while the realistic case does. In future versions, the values in the look-up-tables will be translated from floating point to unsigned int.

### CODE REVIEW

**Comment by dildick** [comment]
@smuzaffar, does @cmsbuild have to be updated so it can run tests on PRs for this repository?

**Comment by smuzaffar** [comment]
@dildick , cmsbuild already knows how to test. Please make sure to update cmssw to make use of these new files. Once you have a cmssw PR then you can comment "please test with ms-data/L1Trigger-CSCTriggerPrimitives#1" to start the tests

**Comment by dildick** [comment]
@smuzaffar That is great to hear. I am working on a pull request to use the new LUTs in the trigger.

**Comment by silviodonato** [comment]
+1

**Comment by mrodozov** [comment]
+externals
new files and a readme, its fine

**Comment by silviodonato** [comment]
merge

**Pull request merged**
