### PR TITLE
Add missing headers, missing columns, and missing GEM-CSC LUTs

### PR DESCRIPTION
**Pull request by dildick**
@rathjd @tahuang1991

### CODE REVIEW

**Comment by dildick** [comment]
Sorry, it's still work in progress. LUTs for CMSSW are missing key columns. LUTs for firmware do not need headers

**Comment by dildick** [comment]
I added missing columns and removed obsolete headers. I think Denis (@rathjd) is still checking a few things as well.

**Comment by dildick** [comment]
@rekovic, @cecilecaillol we're happy with this. Can you initiate the tests, please?

**Comment by cecilecaillol** [comment]
+l1

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
