### PR TITLE
Uodated GEM-CSC triager LUTs

### PR DESCRIPTION
**Pull request by giovanni-mocellin**
This PR contains changes to the GEM-CSC trigger lookup tables to match the ones used in the CSC OTMB FW.

The main changes are:
  - Removal of non-used redundant LUTs for GE1/1 laver 1 and 2
  - Update of the LUT file names, to better reflect their content and usage
  - LUT length increased and fixed to 256 lines - needed for FW

This PR is linked to a PR to be submitted to CMSSW master, which uses these LUT files. A link to this PR will be added to the description of the parallel one in CMSSW.

### CODE REVIEW

**Comment by tvami** [comment]
@cecilecaillol I believe you'd need to sign this too

**Comment by cecilecaillol** [comment]
+l1

**Comment by cecilecaillol** [comment]
please test

**Comment by tvami** [comment]
@cmsbuild please test with https://github.com/cms-sw/cmssw/pull/38373

**Comment by tvami** [comment]
@cmsbuild please test with https://github.com/cms-sw/cmssw/pull/38373

**Comment by tvami** [comment]
@cmsbuild please test with https://github.com/cms-sw/cmssw/pull/38373 and https://github.com/cms-sw/cmssw/pull/38775

**Comment by perrotta** [comment]
merge
Succesfully tested witsh #38373, see https://github.com/cms-sw/cmssw/pull/38373#issuecomment-1189594017

**Pull request merged**
